In [8]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [9]:
dframe_wine = pd.read_csv('winequality-red.csv',sep=';')
dframe_wine.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11,34,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25,67,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15,54,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17,60,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11,34,0.9978,3.51,0.56,9.4,5

In [10]:
def ranker(df):
    df['alc_content_rank'] = np.arange(len(df)) + 1
    return df

## change dataframe 'inplace=True'

In [11]:
dframe_wine.sort('alcohol',ascending = False,inplace=True)

C:\Users\seungjinb\Anaconda\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

### now we have the dataframe sorted

In [12]:
dframe_wine = dframe_wine.groupby('quality').apply(ranker)

In [13]:
dframe_wine.head(10)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,alc_content_rank
652,15.9,0.36,0.65,7.5,0.096,22,71,0.99760,2.98,0.84,14.9,5,1
588,5.0,0.42,0.24,2.0,0.060,19,50,0.99170,3.72,0.74,14.0,8,1
142,5.2,0.34,0.00,1.8,0.050,27,63,0.99160,3.68,0.79,14.0,6,1
144,5.2,0.34,0.00,1.8,0.050,27,63,0.99160,3.68,0.79,14.0,6,2
1270,5.0,0.38,0.01,1.6,0.048,26,60,0.99084,3.70,0.75,14.0,6,3
1269,5.5,0.49,0.03,1.8,0.044,28,87,0.99080,3.50,0.82,14.0,8,2
467,8.8,0.46,0.45,2.6,0.065,7,18,0.99470,3.32,0.79,14.0,6,4
821,4.9,0.42,0.00,2.1,0.048,16,42,0.99154,3.71,0.74,14.0,7,1
1114,5.0,0.40,0.50,4.3,0.046,29,80,0.99020,3.49,0.66,13.6,6,5
1228,5.1,0.42,0.00,1.8,0.044,18,88,0.99157,3.68,0.73,13.6,7,2

In [14]:
dframe_wine.tail(10)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,alc_content_rank
1434,10.2,0.54,0.37,15.4,0.214,55,95,1.00369,3.18,0.77,9.0,6,634
120,7.3,1.07,0.09,1.7,0.178,10,89,0.99620,3.30,0.57,9.0,5,678
1435,10.2,0.54,0.37,15.4,0.214,55,95,1.00369,3.18,0.77,9.0,6,635
1474,9.9,0.50,0.50,13.8,0.205,48,82,1.00242,3.16,0.75,8.8,5,679
1476,9.9,0.50,0.50,13.8,0.205,48,82,1.00242,3.16,0.75,8.8,5,680
371,7.9,0.24,0.40,1.6,0.056,11,25,0.99670,3.32,0.87,8.7,6,636
528,8.2,0.42,0.49,2.6,0.084,32,55,0.99880,3.34,0.75,8.7,6,637
1436,10.0,0.38,0.38,1.6,0.169,27,90,0.99914,3.15,0.65,8.5,5,681
544,14.3,0.31,0.74,1.8,0.075,6,15,1.00080,2.86,0.79,8.4,6,638
517,10.4,0.61,0.49,2.1,0.200,5,16,0.99940,3.16,0.63,8.4,3,10

## NOW finding highest alcohol content for each ranking..!

In [9]:
num_of_qual = dframe_wine['quality'].value_counts()
num_of_qual

5    681
6    638
7    199
4     53
8     18
3     10
dtype: int64

In [10]:
dframe_wine[dframe_wine.alc_content_rank == 1].head(len(num_of_qual))

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,alc_content_rank
652,15.9,0.36,0.65,7.5,0.096,22,71,0.99760,2.98,0.84,14.9,5,1
588,5.0,0.42,0.24,2.0,0.060,19,50,0.99170,3.72,0.74,14.0,8,1
142,5.2,0.34,0.00,1.8,0.050,27,63,0.99160,3.68,0.79,14.0,6,1
821,4.9,0.42,0.00,2.1,0.048,16,42,0.99154,3.71,0.74,14.0,7,1
45,4.6,0.52,0.15,2.1,0.054,8,65,0.99340,3.90,0.56,13.1,4,1
899,8.3,1.02,0.02,3.4,0.084,6,11,0.99892,3.48,0.49,11.0,3,1